WITH TEMP AS(
SELECT
    EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR,
    COUNT(*) AS COUNT
  FROM ANIMAL_OUTS
  GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
    )

 SELECT 
    A.HOUR,
    COALESCE(B.COUNT, 0) COUNT
 FROM ( SELECT 
            LEVEL - 1 AS HOUR
          FROM DUAL
          CONNECT BY LEVEL <= 24
      ) A
 LEFT JOIN TEMP B
 ON A.HOUR = B.HOUR
 ORDER BY HOUR ASC
      


    