-- -- 2022-01의 판매데이터
-- -- 저자별, 카테고리 별 매출액 구하기
-- -- AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES를 출력

-- SELECT 
--     A.AUTHOR_ID,
--     C.AUTHOR_NAME,
--     A.CATEGORY,
--     A.PRICE * B.TOTAL TOTAL_SALES
--   FROM BOOK A
--   JOIN 
--     (SELECT
--         BOOK_ID,
--         SUM(SALES) TOTAL
--       FROM BOOK_SALES
--       WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
--       GROUP BY BOOK_ID) B
--     ON A.BOOK_ID = B.BOOK_ID
--   JOIN AUTHOR C
--     ON A.AUTHOR_ID = C.AUTHOR_ID
--   ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC;



-- 2022-01의 판매데이터
-- 저자별, 카테고리 별 매출액 구하기
-- AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES를 출력

SELECT 
    A.AUTHOR_ID,
    C.AUTHOR_NAME,
    A.CATEGORY,
    SUM(A.PRICE * B.TOTAL) TOTAL_SALES
  FROM BOOK A
  JOIN 
    (SELECT
        BOOK_ID,
        SUM(SALES) TOTAL
      FROM BOOK_SALES
      WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
      GROUP BY BOOK_ID) B
    ON A.BOOK_ID = B.BOOK_ID
  JOIN AUTHOR C
    ON A.AUTHOR_ID = C.AUTHOR_ID
    GROUP BY A.AUTHOR_ID, C.AUTHOR_NAME,A.CATEGORY
  ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC;