-- INGREDIENT_TYPE, 타입별 TOTAL_ORDER을 출력
-- TOTAL_ORDER을 오름차순으로 조회
SELECT
    B.INGREDIENT_TYPE,
    SUM(A.TOTAL_ORDER)
    FROM FIRST_HALF A
    JOIN ICECREAM_INFO B
    ON A.FLAVOR = B.FLAVOR
    GROUP BY INGREDIENT_TYPE;
    
    